import React from 'react';
import { Ionicons } from '@expo/vector-icons';
import { useThemeContext } from '../../theme/ThemeProvider';

type IoniconsName = React.ComponentProps<typeof Ionicons>['name'];

interface IconProps {
  name: IoniconsName;
  size?: number;
  color?: string;
  style?: any;
}

export function Icon({ name, size = 24, color, style }: IconProps) {
  const { theme } = useThemeContext();
  return <Ionicons name={name} size={size} color={color || theme.colors.icon} style={style} />;
}

export const icons = {
  home: 'home-outline' as IoniconsName,
  homeFilled: 'home' as IoniconsName,
  call: 'call-outline' as IoniconsName,
  callFilled: 'call' as IoniconsName,
  chat: 'chatbubble-outline' as IoniconsName,
  chatFilled: 'chatbubble' as IoniconsName,
  people: 'people-outline' as IoniconsName,
  peopleFilled: 'people' as IoniconsName,
  settings: 'settings-outline' as IoniconsName,
  settingsFilled: 'settings' as IoniconsName,
  search: 'search-outline' as IoniconsName,
  add: 'add-outline' as IoniconsName,
  close: 'close-outline' as IoniconsName,
  back: 'chevron-back-outline' as IoniconsName,
  forward: 'chevron-forward-outline' as IoniconsName,
  phone: 'call-outline' as IoniconsName,
  phoneFilled: 'call' as IoniconsName,
  mic: 'mic-outline' as IoniconsName,
  micOff: 'mic-off-outline' as IoniconsName,
  speaker: 'volume-high-outline' as IoniconsName,
  speakerOff: 'volume-mute-outline' as IoniconsName,
  video: 'videocam-outline' as IoniconsName,
  videoOff: 'videocam-off-outline' as IoniconsName,
  message: 'chatbubble-outline' as IoniconsName,
  mail: 'mail-outline' as IoniconsName,
  mailUnread: 'mail-unread-outline' as IoniconsName,
  person: 'person-outline' as IoniconsName,
  personAdd: 'person-add-outline' as IoniconsName,
  star: 'star-outline' as IoniconsName,
  starFilled: 'star' as IoniconsName,
  heart: 'heart-outline' as IoniconsName,
  heartFilled: 'heart' as IoniconsName,
  bookmark: 'bookmark-outline' as IoniconsName,
  share: 'share-outline' as IoniconsName,
  copy: 'copy-outline' as IoniconsName,
  trash: 'trash-outline' as IoniconsName,
  edit: 'create-outline' as IoniconsName,
  check: 'checkmark-outline' as IoniconsName,
  checkCircle: 'checkmark-circle-outline' as IoniconsName,
  alert: 'alert-circle-outline' as IoniconsName,
  info: 'information-circle-outline' as IoniconsName,
  time: 'time-outline' as IoniconsName,
  clock: 'time-outline' as IoniconsName,
  calendar: 'calendar-outline' as IoniconsName,
  location: 'location-outline' as IoniconsName,
  globe: 'globe-outline' as IoniconsName,
  link: 'link-outline' as IoniconsName,
  image: 'image-outline' as IoniconsName,
  camera: 'camera-outline' as IoniconsName,
  folder: 'folder-outline' as IoniconsName,
  document: 'document-outline' as IoniconsName,
  download: 'download-outline' as IoniconsName,
  upload: 'upload-outline' as IoniconsName,
  refresh: 'refresh-outline' as IoniconsName,
  filter: 'filter-outline' as IoniconsName,
  sort: 'swap-vertical-outline' as IoniconsName,
  grid: 'grid-outline' as IoniconsName,
  list: 'list-outline' as IoniconsName,
  menu: 'menu-outline' as IoniconsName,
  more: 'ellipsis-horizontal-outline' as IoniconsName,
  moreVertical: 'ellipsis-vertical-outline' as IoniconsName,
  notifications: 'notifications-outline' as IoniconsName,
  notificationsFilled: 'notifications' as IoniconsName,
  lock: 'lock-closed-outline' as IoniconsName,
  unlock: 'lock-open-outline' as IoniconsName,
  eye: 'eye-outline' as IoniconsName,
  eyeOff: 'eye-off-outline' as IoniconsName,
  shield: 'shield-checkmark-outline' as IoniconsName,
  key: 'key-outline' as IoniconsName,
  logOut: 'log-out-outline' as IoniconsName,
  logIn: 'log-in-outline' as IoniconsName,
  moon: 'moon-outline' as IoniconsName,
  sun: 'sunny-outline' as IoniconsName,
  phonePortrait: 'phone-portrait-outline' as IoniconsName,
  wifi: 'wifi-outline' as IoniconsName,
  bluetooth: 'bluetooth-outline' as IoniconsName,
  battery: 'battery-full-outline' as IoniconsName,
  signal: 'cellular-outline' as IoniconsName,
  airplane: 'airplane-outline' as IoniconsName,
  dialpad: 'keypad-outline' as IoniconsName,
  keypad: 'keypad-outline' as IoniconsName,
  recording: 'recording-outline' as IoniconsName,
  pause: 'pause-outline' as IoniconsName,
  play: 'play-outline' as IoniconsName,
  stop: 'stop-outline' as IoniconsName,
  skipBack: 'play-skip-back-outline' as IoniconsName,
  skipForward: 'play-skip-forward-outline' as IoniconsName,
  volumeHigh: 'volume-high-outline' as IoniconsName,
  volumeLow: 'volume-low-outline' as IoniconsName,
  volumeOff: 'volume-off-outline' as IoniconsName,
  analytics: 'bar-chart-outline' as IoniconsName,
  trending: 'trending-up-outline' as IoniconsName,
  pie: 'pie-chart-outline' as IoniconsName,
  stats: 'stats-chart-outline' as IoniconsName,
};
